webtalk_init -webtalk_dir D:/Facultate/Anul3/CN2/Lucrare1/Lab2_RISC_V_E1/Lucrare/Lucrare.sim/sim_1/behav/xsim/xsim.dir/RISC_V_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec  7 13:40:57 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3f8412f3-f537-4057-a88c-1785ef22ddc7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "90f2a09753fa4c1a9f4c6e47995fdeea" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "76" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "210 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7464_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3489234095 -regid "" -xml D:/Facultate/Anul3/CN2/Lucrare1/Lab2_RISC_V_E1/Lucrare/Lucrare.sim/sim_1/behav/xsim/xsim.dir/RISC_V_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Facultate/Anul3/CN2/Lucrare1/Lab2_RISC_V_E1/Lucrare/Lucrare.sim/sim_1/behav/xsim/xsim.dir/RISC_V_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Facultate/Anul3/CN2/Lucrare1/Lab2_RISC_V_E1/Lucrare/Lucrare.sim/sim_1/behav/xsim/xsim.dir/RISC_V_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
